#!/usr/bin/env bash

libpath="node_modules/tiddlywiki"
bin="tiddlywiki.js"

# clean adjust
rm -rf ${libpath}/plugins/oeyoews
rm -rf ${libpath}/library-template

mkdir ${libpath}/plugins/oeyoews

cp dev/plugins/* ${libpath}/plugins/oeyoews -r
cp src/library-template ${libpath} -r

# node_modules folder
cd ${libpath}
node ${bin} library-template/ --build library
