#!/usr/bin/env bash

# WIP use variable

libpath="node_modules/tiddlywiki"

bin="tiddlywiki.js"

# clean
rm -rf ${libpath}/plugins/oeyoews
rm -rf ${libpath}/library-template

mkdir ${libpath}/plugins/oeyoews

cp dev/plugins/* ${libpath}/plugins/oeyoews -r
cp src/library-template ${libpath} -r

cd ${libpath}
node ${bin} library-template/ --output ../../library --build library
