export default {
  index: [
    "--verbose",
    "--output",
    ".tiddlywiki",
    "--deletetiddlers",
    "$:/StoryList",
    "--render",
    "$:/plugins/tiddlywiki/tiddlyweb/save/offline",
    "index.html",
    "text/plain",
    "--savetiddler",
    "$:/favicon.ico",
    "favicon.ico",
    "--deletetiddlers",
    "$:/StoryList",
  ],
  editions: [
    "--verbose",
    "--output",
    ".tiddlywiki/editions",
    "--render",
    "$:/plugins/tiddlywiki/tiddlyweb/save/offline",
    "index.html",
    "text/plain",
    "--savetiddler",
    "$:/favicon.ico",
    "favicon.ico",
    "--deletetiddlers",
    "$:/StoryList",
  ],
  plugins: [
    "--verbose",
    "--output",
    ".tiddlywiki/plugins",
    "--render",
    "[all[tiddlers+shadows]plugin-type[plugin]author[oeyoews]]",
    "[removeprefix[$:/plugins/oeyoews/]slugify[]addsuffix[.json]]",
    "text/plain",
    "$:/core/templates/json-tiddler",
    "--deletetiddlers",
    "$:/StoryList",
  ],
  themes: [
    "--verbose",
    "--output",
    ".tiddlywiki/themes",
    "--render",
    "[all[tiddlers+shadows]plugin-type[theme]author[NicolasPetton]]",
    "[removeprefix[$:/themes/nico]slugify[]addsuffix[.json]]",
    "text/plain",
    "$:/core/templates/json-tiddler",
    "--deletetiddlers",
    "$:/StoryList",
  ],
  listen: ["--listen", "port=8099", "anon-username=oeyoews"],
  static: [
    "--verbose",
    "--output",
    ".tiddlywiki",
    "--rendertiddlers",
    "[!is[system]]",
    "$:/core/templates/static.tiddler.html",
    "static",
    "text/plain",
    "--rendertiddler",
    "$:/core/templates/static.template.css",
    "static/static.css",
    "text/plain",
    "--savetiddler",
    "$:/favicon.ico",
    "static/favicon.ico",
  ],
  tiddlywikicore: [
    "--output",
    ".tiddlywiki",
    "--render",
    "$:/core/templates/tiddlywiki5.js",
    "[[tiddlywikicore-]addsuffix<version>addsuffix[.js]]",
    "text/plain",
  ],
  library: [
    "--output",
    ".tiddlywiki/library",
    "--makelibrary",
    "$:/UpgradeLibrary",
    "--savelibrarytiddlers",
    "$:/UpgradeLibrary",
    "[prefix[$:/plugins/oeyoews]] [prefix[$:/themes/nico]]",
    "recipes/library/tiddlers/",
    "$:/UpgradeLibrary/List",
    "--savetiddler",
    "$:/UpgradeLibrary/List",
    "recipes/library/tiddlers.json",
    "--rendertiddler",
    "$:/plugins/tiddlywiki/pluginlibrary/library.template.html",
    "index.html",
    "text/plain",
    "--deletetiddlers",
    "[[$:/UpgradeLibrary]] [[$:/UpgradeLibrary/List]]",
  ],
};
