/** @type {import('tw5-typed').ITiddlyWikiInfoJSONBuild} */

export default {
  // build index.html
  index: [
    "--verbose",
    "--output",
    ".tiddlywiki",
    "--deletetiddlers",
    "$:/StoryList",
    "--render",
    "$:/plugins/tiddlywiki/tiddlyweb/save/offline",
    "index.html",
    "text/plain",
    "--savetiddler",
    "$:/favicon.ico",
    "favicon.ico",
    "--deletetiddlers",
    "$:/StoryList",
  ],
  // empty edition
  editions: [
    "--verbose",
    "--output",
    ".tiddlywiki/editions",
    "--render",
    "$:/plugins/tiddlywiki/tiddlyweb/save/offline",
    "index.html",
    "text/plain",
    "--savetiddler",
    "$:/favicon.ico",
    "favicon.ico",
    "--deletetiddlers",
    "$:/StoryList",
  ],
  // Generate plugins json format
  plugins: [
    "--verbose",
    "--output",
    ".tiddlywiki/plugins",
    "--render",
    "[all[tiddlers+shadows]plugin-type[plugin]author[oeyoews]]",
    "[removeprefix[$:/plugins/oeyoews/]slugify[]addsuffix[.json]]",
    "text/plain",
    "$:/core/templates/json-tiddler",
    "--deletetiddlers",
    "$:/StoryList",
  ],
  themes: [
    "--verbose",
    "--output",
    ".tiddlywiki/themes",
    "--render",
    "[all[tiddlers+shadows]plugin-type[theme]author[NicolasPetton]]",
    "[removeprefix[$:/themes/nico]slugify[]addsuffix[.json]]",
    "text/plain",
    "$:/core/templates/json-tiddler",
    "--deletetiddlers",
    "$:/StoryList",
  ],
  // 启动 tiddlywiki
  listen: ["--listen", "port=8099", "anon-username=oeyoews"],
  // 生成 plugin library
  library: [
    "--output",
    ".tiddlywiki/library",
    "--makelibrary",
    "$:/UpgradeLibrary",
    "--savelibrarytiddlers",
    "$:/UpgradeLibrary",
    "[prefix[$:/plugins/oeyoews]] [prefix[$:/themes/nico]]",
    "recipes/library/tiddlers/",
    "$:/UpgradeLibrary/List",
    "--savetiddler",
    "$:/UpgradeLibrary/List",
    "recipes/library/tiddlers.json",
    "--rendertiddler",
    "$:/plugins/tiddlywiki/pluginlibrary/library.template.html",
    "index.html",
    "text/plain",
    "--deletetiddlers",
    "[[$:/UpgradeLibrary]] [[$:/UpgradeLibrary/List]]",
  ],
};
