/**
 * @description tiddlywiki 启用插件列表
 */
export default [
  // 必选依赖
  'tiddlywiki/tiddlyweb',
  'tiddlywiki/filesystem',
  'tiddlywiki/highlight',
  // 'tiddlywiki/katex', // 支持数学公式
  'tiddlywiki/browser-sniff',
  'tiddlywiki/codemirror',
  // 'BTC/tiddlywiki-codemirror-6',
  // codemirror-6 not support this yet
  'tiddlywiki/codemirror-autocomplete',
  'tiddlywiki/codemirror-mode-css',
  'tiddlywiki/codemirror-search-replace',
  'tiddlywiki/codemirror-closebrackets',
  'tiddlywiki/codemirror-mode-markdown',
  'tiddlywiki/codemirror-mode-xml',
  'tiddlywiki/codemirror-mode-javascript',
  'tiddlywiki/freelinks',
  'tiddlywiki/pluginlibrary', // 构建插件
  'tiddlywiki/markdown',
  // 自定义插件
  'oeyoews/neotw-zen-mode',
  'oeyoews/neotw-notranslate',
  'oeyoews/neotw-placeholder',
  'oeyoews/neotw-pwa',
  'oeyoews/neotw-read-files',
  'oeyoews/commandpalette',
  'oeyoews/neotw-icons',
  'oeyoews/neotw-markdown-extensions',
  'oeyoews/neotw-swal2',
  'oeyoews/neotw-copy-code',
  'oeyoews/tiddlywiki-cards',
  'oeyoews/neotw-unsplash',
  'oeyoews/neotw-fetch',
  'oeyoews/neotw-aplayer',
  'oeyoews/tiddlywiki-github-share',
  'oeyoews/tiddlywiki-daylight',
  'oeyoews/tiddlywiki-videos',
  'oeyoews/neotw',
  'oeyoews/neotw-vimjk',
  'oeyoews/NPL',
  'oeyoews/tiddlywiki-back-to-top',
  'oeyoews/neotw-view-image',
  'oeyoews/tiddlywiki-modal-ui',
  'oeyoews/tiddlywiki-motion',
  'oeyoews/tiddlywiki-publish-tiddler',
  'oeyoews/tiddlywiki-tailwindcss-plus',
  'oeyoews/tiddlywiki-tiddler-info',
  'oeyoews/tiddlywiki-gravatar',
  'oeyoews/neotw-homepage',
  'oeyoews/tiddlywiki-readonly',
];
