/**
 * @description tiddlywiki 启用插件列表
 */
export default [
  // 必选依赖
  'tiddlywiki/tiddlyweb',
  'tiddlywiki/filesystem',
  'tiddlywiki/highlight',
  // 支持数学公式
  'tiddlywiki/katex',
  'tiddlywiki/browser-sniff',
  'tiddlywiki/codemirror',
  // 'BTC/tiddlywiki-codemirror-6',
  // codemirror-6 not support this yet
  'tiddlywiki/codemirror-autocomplete',
  'tiddlywiki/codemirror-mode-css',
  'tiddlywiki/codemirror-search-replace',
  'tiddlywiki/codemirror-closebrackets',
  'tiddlywiki/codemirror-mode-markdown',
  'tiddlywiki/codemirror-mode-xml',
  'tiddlywiki/codemirror-mode-javascript',
  'tiddlywiki/freelinks',
  // 构建插件
  'tiddlywiki/pluginlibrary',
  // dom
  // 'tiddlywiki/internals',
  'tiddlywiki/markdown',
  // 自定义插件
  'oeyoews/neotw-permalink',
  'oeyoews/neotw-tw-bot',
  'oeyoews/neotw-pwa',
  'oeyoews/neotw-read-files',
  'oeyoews/commandpalette',
  'oeyoews/neotw-opened-tiddlers',
  'oeyoews/neotw-tour',
  'oeyoews/neotw-icons',
  'oeyoews/neotw-markdown-extensions',
  'oeyoews/neotw-swal2',
  // 'oeyoews/neotw-snippet',
  'oeyoews/neotw-copy-code',
  'oeyoews/neotw-time',
  // 'oeyoews/neotw-deepl',
  'oeyoews/neotw-emoji-picker',
  'oeyoews/neotw-zh-CN',
  'oeyoews/neotw-battery',
  'oeyoews/tiddlywiki-cards',
  'oeyoews/neotw-type',
  'oeyoews/neotw-gli',
  'oeyoews/neotw-unsplash',
  'oeyoews/neotw-fetch',
  'oeyoews/neotw-aplayer',
  'oeyoews/neotw-lodash',
  'oeyoews/tiddlywiki-tid2png',
  'oeyoews/tiddlywiki-github-share',
  'oeyoews/tiddlywiki-axios',
  'oeyoews/tiddlywiki-daylight',
  'oeyoews/neotw-confetti',
  'oeyoews/tiddlywiki-videos',
  'oeyoews/neotw',
  'oeyoews/neotw-hitokoto',
  'oeyoews/neotw-vimjk',
  'oeyoews/NPL',
  'oeyoews/tiddlywiki-back-to-top',
  // 'oeyoews/tiddlywiki-edition-macro',
  // lightbox plugins
  'oeyoews/neotw-view-image',
  // 'oeyoews/tiddlywiki-fancybox-ui',
  'oeyoews/tiddlywiki-keyboard-hint',
  'oeyoews/tiddlywiki-modal-ui',
  'oeyoews/tiddlywiki-motion',
  'oeyoews/tiddlywiki-publish-tiddler',
  'oeyoews/tiddlywiki-tailwindcss-plus',
  'oeyoews/tiddlywiki-tiddler-info',
  'oeyoews/tiddlywiki-gravatar',
  'oeyoews/tiddlywiki-sounds',
  'oeyoews/neotw-homepage',
  'oeyoews/tiddlywiki-readonly',
];
